SET default_transaction_read_only = off;

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

CREATE ROLE backend;
ALTER ROLE backend WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS PASSWORD 'SCRAM-SHA-256$4096:AiJdw9os4I6mtYoswwRVvQ==$23zaOrLPYYF1IFgazHxwwgE5zf81IvFFHDUejLlyrtw=:+aw62Nltjt3959KA4cZLiieqCNyE/2Odfi14CbTmYmQ=';
CREATE ROLE frontend;
ALTER ROLE frontend WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS PASSWORD 'SCRAM-SHA-256$4096:QqoicVyBaM3pjdL/8fQPpQ==$zsaWl6L+P0drAOk0AZF6Ovmg2SK4RPpMG0aObctjwkk=:L9NhO/bMss7JiAzq937un45NGH8O1bJTYkaMmFrCf84=';
CREATE ROLE admin;
ALTER ROLE admin WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS PASSWORD 'SCRAM-SHA-256$4096:9UB/Jh7Z5GoIiJN4iCmijQ==$LaC4FyzU0pvquEdVodC28bw+Mo5ijaBF2gn0z9BDWPM=:SwtPNG+OQi3mxxCoSJgM2PkzI6eW767xe56MrSVsJEM=';

ALTER ROLE postgres WITH PASSWORD NULL;
